# Generated by Django 2.2 on 2019-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_str', models.CharField(max_length=500)),
                ('qr_type', models.CharField(max_length=20)),
            ],
        ),
    ]
