# Generated by Django 2.2 on 2019-05-12 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='qrcodes'),
            preserve_default=False,
        ),
    ]
