# Generated by Django 2.2 on 2019-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_qrcode_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='hashed_str',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
