# Generated by Django 2.2 on 2019-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0003_auto_20190512_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(null=True, upload_to='qrcodes'),
        ),
    ]
