# Generated by Django 2.2.1 on 2019-05-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0004_auto_20190512_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRWebModel',
            fields=[
                ('hashed_str', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('qr_type', models.CharField(max_length=20)),
                ('qr_image', models.ImageField(null=True, upload_to='qrcodes')),
            ],
        ),
    ]
