# Generated by Django 2.2.1 on 2019-05-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0005_qrwebmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRWebModel',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.CharField(max_length=500),
        ),
    ]
