# Generated by Django 2.2.1 on 2019-05-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0006_auto_20190530_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_type',
        ),
    ]
