# Generated by Django 2.2.1 on 2019-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0007_remove_qrcode_qr_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode_Web',
            fields=[
                ('hashed_str', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('qr_image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode_Wifi',
            fields=[
                ('hashed_str', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('qr_image', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='QRCode',
            new_name='QRCode_VCard',
        ),
    ]
