# Generated by Django 2.2 on 2019-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0009_auto_20190530_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode_web',
            name='hashed_str',
        ),
        migrations.AddField(
            model_name='qrcode_web',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode_web',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode_web',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
