# Generated by Django 2.2 on 2019-05-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0011_remove_qrcode_web_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode_web',
            name='id',
        ),
        migrations.AddField(
            model_name='qrcode_vcard',
            name='qr_id',
            field=models.AutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode_web',
            name='qr_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode_wifi',
            name='qr_id',
            field=models.AutoField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode_vcard',
            name='hashed_str',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='qrcode_wifi',
            name='hashed_str',
            field=models.CharField(max_length=500),
        ),
    ]
