# Generated by Django 2.2 on 2019-05-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0012_auto_20190531_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode_vcard',
            old_name='hashed_str',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='qrcode_wifi',
            old_name='hashed_str',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='qrcode_vcard',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='qrcode_wifi',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='qrcode_vcard',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qrcode_vcard',
            name='firstname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qrcode_vcard',
            name='lastname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qrcode_vcard',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='qrcode_wifi',
            name='wifiname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qrcode_wifi',
            name='wifipassword',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qrcode_wifi',
            name='wifitype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
